# Generated by Django 5.0.1 on 2024-01-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Habilitado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Admin'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acceso al Dash'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_superadmin',
            field=models.BooleanField(default=False, verbose_name='SuperAdmin'),
        ),
    ]
