# Generated by Django 5.0.1 on 2024-01-25 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuarios', '0003_alter_usuario_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfil/usuarios/'),
        ),
    ]
