# Generated by Django 5.0.1 on 2024-01-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas_usuarios', '0004_alter_usuario_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
    ]
