name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: path/to/your/django/project

    - name: Run Migrations
      run: |
        python manage.py migrate
      working-directory: path/to/your/django/project

    - name: Run Tests
      run: |
        python manage.py test
      working-directory: path/to/your/django/project

    - name: Analyze with SonarQube
      run: |
        sonar-scanner -Dsonar.projectKey=GPDARO -Dsonar.organization=developerdaro -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
