name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Ajusta la versión de Python según tu proyecto

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API/requirements.txt

    - name: Install SonarScanner
      run: |
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 9BFAB0AA
        echo "deb http://repos.sonarsource.com/sonarqube-scanner-cli/deb/ stable main" | sudo tee -a /etc/apt/sources.list
        sudo apt-get update && sudo apt-get install -y sonar-scanner

    - name: Run SonarQube analysis
      run: |
        sonar-scanner \
          -Dsonar.projectKey=GPDARO \
          -Dsonar.organization=developerdaro \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
