name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Install SonarScanner
      run: |
        curl -L https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.2.2472-linux.zip -o sonar-scanner-cli.zip
        unzip sonar-scanner-cli.zip
        export PATH=$PATH:$(pwd)/sonar-scanner-4.6.2.2472-linux/bin

    - name: Build and Analyze with SonarQube
      run: |
        ./gradlew build
        sonar-scanner \
          -Dsonar.projectKey=GPDARO \
          -Dsonar.organization=developerdaro \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
