name: SonarCloud Analysis

on:
  push:
    branches:
      - master

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8  # Puedes ajustar la versión de Python según tu proyecto

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API/requirements.txt

    - name: Run SonarQube analysis
      run: |
        # Asegúrate de que 'sonar-scanner' esté instalado en tu sistema o ajusta esta parte según las instrucciones de instalación de SonarQube
        sonar-scanner \
          -Dsonar.projectKey=GPDARO \
          -Dsonar.organization=developerdaro \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=$SONAR_TOKEN
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
