name: Pylint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        pylint --output-format=parseable API/apps/cuentas_usuarios/models.py
        # pylint --output-format=parseable API/apps/actividades/**/*.py
        # pylint --output-format=parseable API/apps/finanzas/**/*.py
