name: Pylint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        pylint --output-format=parseable API/apps/cuentas_usuarios/models.py

    - name: Add comments to Pull Request
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const github = require('@actions/github');

          const token = process.env.GITHUB_TOKEN;
          const octokit = github.getOctokit(token);

          const prNumber = fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
          const body = 'Your pylint score is: ...';  // Reemplaza con tu puntuación o estadísticas

          await octokit.issues.createComment({
            owner: github.context.repo.owner,
            repo: github.context.repo.repo,
            issue_number: prNumber,
            body: body
          });
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
