name: Pylint

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r API/requirements.txt

    - name: Run Pylint
      run: |
        pylint API/gpdaro_project/apps/cuentas_usuarios/*.py
        pylint API/gpdaro_project/apps/actividades/*.py
        pylint API/gpdaro_project/apps/finanzas/*.py
