name: Pylint

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint

    - name: Run Pylint
      run: |
        pylint --output-format=parseable API/apps/cuentas_usuarios/models.py

    - name: Add comment to Pull Request
      uses: pullreminders/comment-on-pr@v1
      with:
        message: 'Your pylint score is: ...'  # Reemplaza con tu puntuación o estadísticas
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
