- name: Run Pylint
  uses: github/codeql-action/checkout@v1
- name: Set up Python
  uses: actions/setup-python@v2
  with:
    python-version: '3.x'  # Reemplaza 'x' con la versión de Python que necesitas
- name: Install dependencies
  run: |
    python -m pip install --upgrade pip
    pip install pylint
- name: Run pylint
  run: |
    pylint API/apps/cuentas_usuarios/**/*.py
